services:
  nestproject:
    container_name: 'sanabelProject'
    restart: always
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: ./src/DockerFile
    ports:
      - '9000:9000'
    volumes:
      - .:/home/node/app
    links:
      - db
    depends_on:
      - db
    networks:
      - backend

  db:
    image: mysql
    container_name: sanabel-project-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: sanabel
        # Set the database name
    ports:
      - 3306:3306
    networks:
      - backend

  phpmyadmin:
    platform: linux/x86_64
    restart: always
    container_name: 'phpmyadmin-sanabelproject'
    image: phpmyadmin/phpmyadmin
    env_file:
      - ./.env
    links:
      - db:db
    ports:
      - '8082:80'
    environment:
      MYSQL_USERNAME: 'root'
      MYSQL_ROOT_PASSWORD: 'test123'
      PMA_HOST: db
    networks:
      - backend

volumes:
  sanabel-project-mysql:
    driver: local
  phpmyadmin:
    driver: local

networks:
  backend:
    driver: bridge
