# Use the official Node.js 20 image as the base image
FROM node:20

# Set the working directory inside the container
WORKDIR /home/node/app
# Use the official Node.js 20 image as the base image
FROM node:20

# Set the working directory inside the container
WORKDIR /home/node/app

# Install nest cli globally
RUN npm install -g @nestjs/cli

# Copy the package.json and package-lock.json files to the container
COPY package.json ./

# Install the dependencies
RUN npm install -g pnpm
RUN pnpm install --force

# Copy the rest of the application code
COPY . .

# Expose the port on which your NestJS app runs
# EXPOSE 90

# Start the NestJS app
CMD ["pnpm", "run", "build"]
CMD ["pnpm", "run", "start:dev"]
# Install nest cli globally
RUN npm install -g @nestjs/cli

# Copy the package.json and package-lock.json files to the container
COPY package.json ./

# Install the dependencies
RUN npm install -g pnpm
RUN pnpm install --force

# Copy the rest of the application code
COPY . .

# Expose the port on which your NestJS app runs
# EXPOSE 90

# Start the NestJS app
CMD ["pnpm", "run", "build"]
CMD ["pnpm", "run", "start:dev"]